---
# tasks file for proxy
- name: Установка Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Настройка проксирования
  template:
    src: proxy_nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Включение и запуск Nginx
  service:
    name: nginx
    state: started
    enabled: yes
